package com.zend.ide.w.a;

public class cc
{
  private static int[] a;

  public static String a(String paramString, char paramChar)
  {
    if (paramChar == 'A')
    {
      StringBuffer localStringBuffer = new StringBuffer("A");
      for (int i = 0; i < paramString.length(); i++)
      {
        int j = paramString.charAt(i);
        int k = (byte)(a[(j & 0xFF)] & 0xFF);
        localStringBuffer.append((char)k);
      }
      return localStringBuffer.toString();
    }
    return null;
  }

  static
  {
    int[] arrayOfInt = new int[256];
    for (int i = 0; i < 32; i++)
      arrayOfInt[i] = i;
    arrayOfInt[(i++)] = 114;
    arrayOfInt[(i++)] = 120;
    arrayOfInt[(i++)] = 53;
    arrayOfInt[(i++)] = 79;
    arrayOfInt[(i++)] = 96;
    arrayOfInt[(i++)] = 109;
    arrayOfInt[(i++)] = 72;
    arrayOfInt[(i++)] = 108;
    arrayOfInt[(i++)] = 70;
    arrayOfInt[(i++)] = 64;
    arrayOfInt[(i++)] = 76;
    arrayOfInt[(i++)] = 67;
    arrayOfInt[(i++)] = 116;
    arrayOfInt[(i++)] = 74;
    arrayOfInt[(i++)] = 68;
    arrayOfInt[(i++)] = 87;
    arrayOfInt[(i++)] = 111;
    arrayOfInt[(i++)] = 52;
    arrayOfInt[(i++)] = 75;
    arrayOfInt[(i++)] = 119;
    arrayOfInt[(i++)] = 49;
    arrayOfInt[(i++)] = 34;
    arrayOfInt[(i++)] = 82;
    arrayOfInt[(i++)] = 81;
    arrayOfInt[(i++)] = 95;
    arrayOfInt[(i++)] = 65;
    arrayOfInt[(i++)] = 112;
    arrayOfInt[(i++)] = 86;
    arrayOfInt[(i++)] = 118;
    arrayOfInt[(i++)] = 110;
    arrayOfInt[(i++)] = 122;
    arrayOfInt[(i++)] = 105;
    arrayOfInt[(i++)] = 41;
    arrayOfInt[(i++)] = 57;
    arrayOfInt[(i++)] = 83;
    arrayOfInt[(i++)] = 43;
    arrayOfInt[(i++)] = 46;
    arrayOfInt[(i++)] = 102;
    arrayOfInt[(i++)] = 40;
    arrayOfInt[(i++)] = 89;
    arrayOfInt[(i++)] = 38;
    arrayOfInt[(i++)] = 103;
    arrayOfInt[(i++)] = 45;
    arrayOfInt[(i++)] = 50;
    arrayOfInt[(i++)] = 42;
    arrayOfInt[(i++)] = 123;
    arrayOfInt[(i++)] = 91;
    arrayOfInt[(i++)] = 35;
    arrayOfInt[(i++)] = 125;
    arrayOfInt[(i++)] = 55;
    arrayOfInt[(i++)] = 54;
    arrayOfInt[(i++)] = 66;
    arrayOfInt[(i++)] = 124;
    arrayOfInt[(i++)] = 126;
    arrayOfInt[(i++)] = 59;
    arrayOfInt[(i++)] = 47;
    arrayOfInt[(i++)] = 92;
    arrayOfInt[(i++)] = 71;
    arrayOfInt[(i++)] = 115;
    arrayOfInt[(i++)] = 78;
    arrayOfInt[(i++)] = 88;
    arrayOfInt[(i++)] = 107;
    arrayOfInt[(i++)] = 106;
    arrayOfInt[(i++)] = 56;
    arrayOfInt[(i++)] = 36;
    arrayOfInt[(i++)] = 121;
    arrayOfInt[(i++)] = 117;
    arrayOfInt[(i++)] = 104;
    arrayOfInt[(i++)] = 101;
    arrayOfInt[(i++)] = 100;
    arrayOfInt[(i++)] = 69;
    arrayOfInt[(i++)] = 73;
    arrayOfInt[(i++)] = 99;
    arrayOfInt[(i++)] = 63;
    arrayOfInt[(i++)] = 94;
    arrayOfInt[(i++)] = 93;
    arrayOfInt[(i++)] = 39;
    arrayOfInt[(i++)] = 37;
    arrayOfInt[(i++)] = 61;
    arrayOfInt[(i++)] = 48;
    arrayOfInt[(i++)] = 58;
    arrayOfInt[(i++)] = 113;
    arrayOfInt[(i++)] = 32;
    arrayOfInt[(i++)] = 90;
    arrayOfInt[(i++)] = 44;
    arrayOfInt[(i++)] = 98;
    arrayOfInt[(i++)] = 60;
    arrayOfInt[(i++)] = 51;
    arrayOfInt[(i++)] = 33;
    arrayOfInt[(i++)] = 97;
    arrayOfInt[(i++)] = 62;
    arrayOfInt[(i++)] = 77;
    arrayOfInt[(i++)] = 84;
    arrayOfInt[(i++)] = 80;
    arrayOfInt[(i++)] = 85;
    arrayOfInt[(i++)] = 223;
    arrayOfInt[(i++)] = 225;
    arrayOfInt[(i++)] = 216;
    arrayOfInt[(i++)] = 187;
    arrayOfInt[(i++)] = 166;
    arrayOfInt[(i++)] = 229;
    arrayOfInt[(i++)] = 189;
    arrayOfInt[(i++)] = 222;
    arrayOfInt[(i++)] = 188;
    arrayOfInt[(i++)] = 141;
    arrayOfInt[(i++)] = 249;
    arrayOfInt[(i++)] = 148;
    arrayOfInt[(i++)] = 200;
    arrayOfInt[(i++)] = 184;
    arrayOfInt[(i++)] = 136;
    arrayOfInt[(i++)] = 248;
    arrayOfInt[(i++)] = 190;
    arrayOfInt[(i++)] = 199;
    arrayOfInt[(i++)] = 170;
    arrayOfInt[(i++)] = 181;
    arrayOfInt[(i++)] = 204;
    arrayOfInt[(i++)] = 138;
    arrayOfInt[(i++)] = 232;
    arrayOfInt[(i++)] = 218;
    arrayOfInt[(i++)] = 183;
    arrayOfInt[(i++)] = 255;
    arrayOfInt[(i++)] = 234;
    arrayOfInt[(i++)] = 220;
    arrayOfInt[(i++)] = 247;
    arrayOfInt[(i++)] = 213;
    arrayOfInt[(i++)] = 203;
    arrayOfInt[(i++)] = 226;
    arrayOfInt[(i++)] = 193;
    arrayOfInt[(i++)] = 174;
    arrayOfInt[(i++)] = 172;
    arrayOfInt[(i++)] = 228;
    arrayOfInt[(i++)] = 252;
    arrayOfInt[(i++)] = 217;
    arrayOfInt[(i++)] = 201;
    arrayOfInt[(i++)] = 131;
    arrayOfInt[(i++)] = 230;
    arrayOfInt[(i++)] = 197;
    arrayOfInt[(i++)] = 211;
    arrayOfInt[(i++)] = 145;
    arrayOfInt[(i++)] = 238;
    arrayOfInt[(i++)] = 161;
    arrayOfInt[(i++)] = 179;
    arrayOfInt[(i++)] = 160;
    arrayOfInt[(i++)] = 212;
    arrayOfInt[(i++)] = 207;
    arrayOfInt[(i++)] = 221;
    arrayOfInt[(i++)] = 254;
    arrayOfInt[(i++)] = 173;
    arrayOfInt[(i++)] = 202;
    arrayOfInt[(i++)] = 146;
    arrayOfInt[(i++)] = 224;
    arrayOfInt[(i++)] = 151;
    arrayOfInt[(i++)] = 140;
    arrayOfInt[(i++)] = 196;
    arrayOfInt[(i++)] = 205;
    arrayOfInt[(i++)] = 130;
    arrayOfInt[(i++)] = 135;
    arrayOfInt[(i++)] = 133;
    arrayOfInt[(i++)] = 143;
    arrayOfInt[(i++)] = 246;
    arrayOfInt[(i++)] = 192;
    arrayOfInt[(i++)] = 159;
    arrayOfInt[(i++)] = 244;
    arrayOfInt[(i++)] = 239;
    arrayOfInt[(i++)] = 185;
    arrayOfInt[(i++)] = 168;
    arrayOfInt[(i++)] = 215;
    arrayOfInt[(i++)] = 144;
    arrayOfInt[(i++)] = 139;
    arrayOfInt[(i++)] = 165;
    arrayOfInt[(i++)] = 180;
    arrayOfInt[(i++)] = 157;
    arrayOfInt[(i++)] = 147;
    arrayOfInt[(i++)] = 186;
    arrayOfInt[(i++)] = 214;
    arrayOfInt[(i++)] = 176;
    arrayOfInt[(i++)] = 227;
    arrayOfInt[(i++)] = 231;
    arrayOfInt[(i++)] = 219;
    arrayOfInt[(i++)] = 169;
    arrayOfInt[(i++)] = 175;
    arrayOfInt[(i++)] = 156;
    arrayOfInt[(i++)] = 206;
    arrayOfInt[(i++)] = 198;
    arrayOfInt[(i++)] = 129;
    arrayOfInt[(i++)] = 164;
    arrayOfInt[(i++)] = 150;
    arrayOfInt[(i++)] = 210;
    arrayOfInt[(i++)] = 154;
    arrayOfInt[(i++)] = 177;
    arrayOfInt[(i++)] = 134;
    arrayOfInt[(i++)] = 127;
    arrayOfInt[(i++)] = 182;
    arrayOfInt[(i++)] = 128;
    arrayOfInt[(i++)] = 158;
    arrayOfInt[(i++)] = 208;
    arrayOfInt[(i++)] = 162;
    arrayOfInt[(i++)] = 132;
    arrayOfInt[(i++)] = 167;
    arrayOfInt[(i++)] = 209;
    arrayOfInt[(i++)] = 149;
    arrayOfInt[(i++)] = 241;
    arrayOfInt[(i++)] = 153;
    arrayOfInt[(i++)] = 251;
    arrayOfInt[(i++)] = 237;
    arrayOfInt[(i++)] = 236;
    arrayOfInt[(i++)] = 171;
    arrayOfInt[(i++)] = 195;
    arrayOfInt[(i++)] = 243;
    arrayOfInt[(i++)] = 233;
    arrayOfInt[(i++)] = 253;
    arrayOfInt[(i++)] = 240;
    arrayOfInt[(i++)] = 194;
    arrayOfInt[(i++)] = 250;
    arrayOfInt[(i++)] = 191;
    arrayOfInt[(i++)] = 155;
    arrayOfInt[(i++)] = 142;
    arrayOfInt[(i++)] = 137;
    arrayOfInt[(i++)] = 245;
    arrayOfInt[(i++)] = 235;
    arrayOfInt[(i++)] = 163;
    arrayOfInt[(i++)] = 242;
    arrayOfInt[(i++)] = 178;
    arrayOfInt[(i++)] = 152;
    a = arrayOfInt;
  }
}

/* Location:           C:\Program Files\Zend\ZendStudio-5.5.1\bin\ZendIDE.jar
 * Qualified Name:     com.zend.ide.w.a.cc
 * JD-Core Version:    0.6.0
 */