package com.zend.ide.gb;

import com.a.f;
import com.zend.ide.f.bp;
import com.zend.ide.f.s;
import com.zend.ide.gb.b.a;
import com.zend.ide.gb.b.b;
import com.zend.ide.gb.b.c;
import com.zend.ide.m.bf;
import com.zend.ide.m.bh;
import com.zend.ide.m.bi;
import com.zend.ide.m.v;
import com.zend.ide.m.z;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class g
{
  private i a;
  ArrayList b = null;
  ArrayList c = null;

  public g(i parami)
  {
    this.a = parami;
  }

  public void a(b paramb)
  {
    ArrayList localArrayList = b(paramb);
    String str = paramb.g();
    if (str.trim().equals(""))
      str = a(paramb.c());
    this.a.f();
    com.a.d locald = l.a(paramb.b(), str, localArrayList, paramb.a(), paramb.e(), paramb.f());
    this.a.a(l.d());
    try
    {
      f.a(paramb.c(), locald, "WSDL file generated by Zend Studio.");
      this.a.g();
    }
    catch (IOException localIOException)
    {
      localIOException.printStackTrace();
    }
  }

  private String a(String paramString)
  {
    String str = paramString;
    int i = str.lastIndexOf(File.separator);
    int j = str.indexOf(".");
    if (i < j)
      str = str.substring(i + 1, j);
    else
      str = str.substring(i + 1);
    return str;
  }

  public void a(b paramb, ArrayList paramArrayList1, ArrayList paramArrayList2, boolean paramBoolean)
  {
    if (paramBoolean)
    {
      paramArrayList1.clear();
      paramArrayList2.clear();
      this.b = paramArrayList1;
      this.c = paramArrayList2;
    }
    a(paramb, paramBoolean);
  }

  private void a(b paramb, boolean paramBoolean)
  {
    ArrayList localArrayList1 = paramb.b();
    if (localArrayList1 == null)
      return;
    for (int i = 0; i < localArrayList1.size(); i++)
    {
      c localc = (c)localArrayList1.get(i);
      ArrayList localArrayList2 = localc.e();
      for (int j = 0; j < localArrayList2.size(); j++)
      {
        localObject = (a)localArrayList2.get(j);
        v localv = bp.d().b().a(localc.b(), ((a)localObject).a(), false);
        if (localv == null)
          continue;
        bh[] arrayOfbh = localv.h();
        ((a)localObject).a(arrayOfbh);
        if (localv.a() != null)
          ((a)localObject).a(localv.a().a());
        if (!paramBoolean)
          continue;
        for (int m = 0; m < arrayOfbh.length; m++)
          a(arrayOfbh[m], localc.b());
      }
      if (!localc.c())
        continue;
      bf localbf = bp.d().b().a(localc.b());
      if (localbf == null)
        continue;
      Object localObject = localbf.d();
      localc.a(localObject);
      if (!paramBoolean)
        continue;
      for (int k = 0; k < localObject.length; k++)
        a(localObject[k], localbf.a());
    }
  }

  private void a(bh parambh, String paramString)
  {
    bi[] arrayOfbi = parambh.c();
    for (int i = 0; i < arrayOfbi.length; i++)
    {
      String str2 = arrayOfbi[i].g();
      if ((str2 == null) || (str2.equals("unknown_type")))
        continue;
      a(str2, paramString);
    }
    String str1 = parambh.d();
    if ((str1 == null) || (str1.equals("unknown_type")))
      return;
    a(str1, paramString);
  }

  private void a(String paramString1, String paramString2)
  {
    if ((paramString1 == null) || (!b(paramString1)))
      return;
    v localv = bp.d().b().a(paramString2, paramString1, false);
    if (localv == null)
    {
      if (!this.b.contains(paramString1))
      {
        this.b.add(paramString1);
        this.c.add(paramString2);
      }
      return;
    }
    z[] arrayOfz = localv.g();
    for (int i = 0; i < arrayOfz.length; i++)
      a(arrayOfz[i].c(), paramString2);
  }

  private boolean b(String paramString)
  {
    return (!paramString.equals("boolean")) && (!paramString.equals("bool")) && (!paramString.equals("integer")) && (!paramString.equals("int")) && (!paramString.equals("float")) && (!paramString.equals("double")) && (!paramString.equals("string")) && (!paramString.equals("array")) && (!paramString.equals("mixed")) && (!paramString.equals("void"));
  }

  private ArrayList b(b paramb)
  {
    e.b().c();
    ArrayList localArrayList1 = paramb.a();
    ArrayList localArrayList2 = new ArrayList();
    if (localArrayList1 == null)
      return localArrayList2;
    for (int i = 0; i < localArrayList1.size(); i++)
    {
      com.zend.ide.gb.b.d locald = (com.zend.ide.gb.b.d)localArrayList1.get(i);
      String str = locald.b();
      if ((str == null) || (str.trim().equals("")))
        continue;
      int j = localArrayList2.indexOf(str);
      if (j == -1)
      {
        j = localArrayList2.size();
        localArrayList2.add(str);
        e.b().a("typens" + j);
      }
      e.b().a("typens" + j, locald.a());
    }
    return localArrayList2;
  }

  public bf c(String paramString)
  {
    return bp.d().b().a(paramString);
  }

  public void a(String paramString, int paramInt)
  {
    this.a.a(paramString, paramInt);
  }
}

/* Location:           C:\Program Files\Zend\ZendStudio-5.5.1\bin\ZendIDE.jar
 * Qualified Name:     com.zend.ide.gb.g
 * JD-Core Version:    0.6.0
 */